version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
     - eventstore
     - readmodelsdb

  eventstore:
    image: mongo:4.0
    ports:
      - "28018:27017"

  readmodelsdb:
    image: mongo:4.0
    ports:
      - "28019:27017"
