<?php
/**
 * Copyright (c) 2017 Constantin Galbenu <xprt64@gmail.com>
 */

namespace Domain\Cqrs;

use Gica\Cqrs\Event\EventSubscriber\EventSubscriberByMap;

/**
 * --- generated by /work/github/xprt64/todo-cqrs-es/vendor/xprt64/cqrs-es/src/Gica/Cqrs/CodeGeneration/CodeGenerator.php at 2017-02-16T17:24:35+02:00 ---
 */
class WriteSideEventSubscriber extends EventSubscriberByMap
{
    protected function getMap():array
    {
        return [

        ];
    }
}