<?php
/**
 * Copyright (c) 2017 Constantin Galbenu <xprt64@gmail.com>
 */

namespace Domain\Cqrs;

use Gica\Cqrs\Command\CommandValidation\CommandValidatorSubscriberByMap;

/**
 * --- generated by /work/github/xprt64/todo-cqrs-es/vendor/xprt64/cqrs-es/src/Gica/Cqrs/CodeGeneration/CodeGenerator.php at 2017-03-27T21:05:31+03:00 ---
 */
class CommandValidatorSubscriber extends CommandValidatorSubscriberByMap
{
    protected function getCommandHandlersDefinitions():array
    {
        return [

        ];
    }
}