<?php
/**
 * Copyright (c) 2017 Constantin Galbenu <xprt64@gmail.com>
 */

namespace Infrastructure\Cqrs;

use Dudulina\Event\EventSubscriber\EventSubscriberByMap;

/**
 * --- generated by /work/github/xprt64/todo-cqrs-es/vendor/xprt64/dudulina/src/Dudulina/CodeGeneration/CodeGenerator.php at 2018-02-28T16:54:55+02:00 ---
 */
class EventSubscriber extends EventSubscriberByMap
{
    protected function getMap():array
    {
        return [
            \Domain\Write\Todo\TodoAggregate\Event\ANewTodoWasAdded::class => [
                [\Domain\Read\Todo\TodoList::class, 'onANewTodoWasAdded'],
            ],

            \Domain\Write\Todo\TodoAggregate\Event\ATodoWasMarkedAsDone::class => [
                [\Domain\Read\Todo\TodoList::class, 'onATodoWasMarkedAsDone'],
            ],

            \Domain\Write\Todo\TodoAggregate\Event\ANewTodoWasRenamed::class => [
                [\Domain\Read\Todo\TodoList::class, 'onANewTodoWasRenamed'],
            ],

            \Domain\Write\Todo\TodoAggregate\Event\ATodoWasUnmarkedAsDone::class => [
                [\Domain\Read\Todo\TodoList::class, 'onATodoWasUnmarkedAsDone'],
            ],

            \Domain\Write\Todo\TodoAggregate\Event\ATodoWasDeleted::class => [
                [\Domain\Read\Todo\TodoList::class, 'onATodoWasDeleted'],
            ],
        ];
    }
}