<?php
/**
 * Copyright (c) 2017 Constantin Galbenu <xprt64@gmail.com>
 */

namespace Infrastructure\Cqrs;

use Dudulina\Event\EventSubscriber\EventSubscriberByMap;

/**
 * --- generated by /work/github/xprt64/todo-cqrs-es/vendor/xprt64/dudulina/src/Dudulina/CodeGeneration/CodeGenerator.php at 2018-02-28T16:54:55+02:00 ---
 */
class SagaEventSubscriber extends EventSubscriberByMap
{
    protected function getMap():array
    {
        return [
            \Domain\Write\Todo\TodoAggregate\Event\ANewTodoWasAdded::class => [
                [\Domain\Write\Todo\DuplicateTodoDetection\RenameDuplicateTodoSaga::class, 'processANewTodoWasAdded'],
            ],
        ];
    }
}