<?php
/**
 * Copyright (c) 2017 Constantin Galbenu <xprt64@gmail.com>
 */

namespace Infrastructure\Cqrs;

use Dudulina\Event\EventSubscriber\EventSubscriberByMap;

/**
 * --- generated by /work/github/xprt64/todo-cqrs-es/vendor/xprt64/cqrs-es/src/Gica/Cqrs/CodeGeneration/CodeGenerator.php at 2017-03-27T21:11:52+03:00 ---
 */
class WriteSideEventSubscriber extends EventSubscriberByMap
{
    protected function getMap():array
    {
        return [

        ];
    }
}