<?php
$this->headLink()
    ->appendStylesheet('/theme/css/bootstrap.min.css')
    ->appendStylesheet('/theme/css/portfolio-item.css')
    ->appendStylesheet('/css/default.css');

$this->headScript()
    ->appendFile('https://code.jquery.com/jquery-2.1.4.min.js')
    ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->appendFile('/js/network.js');


?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <?php echo $this->headTitle('CQRS+ES Todo App')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <style>
        body {
            padding-top: 60px;
        }

        .app {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        .app-content {
            flex: 1;
        }

        .app-footer {
            padding-bottom: 1em;
        }

        .zf-green, h2 a {
            color: #68b604;
        }
    </style>
</head>
<body class="app">

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Home</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="https://github.com/xprt64/dudulina" target="_blank">
                        <i class="fa fa-book"></i> Github CQRS+ES
                    </a>
                </li>
                <li>
                    <a href="https://github.com/xprt64/todosample-cqrs-es" target="_blank">
                        <i class="fa fa-book"></i> Github Todo
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('api.ping') ?>">
                        Ping Test
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">

    <?php echo $this->content ?>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Constantin GALBENU &lt;gica.galbenu
                    <script>document.write('@');</script>
                    gmail.com&gt;</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->


<?php echo $this->inlineScript(); ?>
</body>
</html>
